EntitlementManagement - Add Types, move catalogs and packages to 1.0 Stable
manicminer/hamilton pull request #133
Opened 2021-12-11 18:40 UTC by kaovd

Bugfixes and make stable where possible parts of the EntitlementManagement scopes

ODataTypes are required to be passed on the UserSet Struct

2021-12-17 13:21 UTC, kaovd commented
I also need to add "#microsoft.graph.question"to questions Struct, will do this later

2021-12-20 09:54 UTC, manicminer requested changes
Hi @kaovd, thanks for working on this! I've made a couple of notes on compatibility between the 1.0 and beta APIs if you can consider these? There may be other divergences I have missed. If it's impractical to maintain compatibility (e.g. perhaps the beta API isn't working right) then that's fine, but for now if we can that'd be good.

2021-12-20 09:54 UTC, manicminer commented on msgraph/models.go
> +	State               AccessPackageCatalogState `json:"state,omitempty"`
As above, could we keep both fields for now in order to maintain compatibility with the beta API? I'm assuming the beta docs are correct and the field is still called `catalogStatus` in the beta model?

2021-12-20 09:54 UTC, manicminer commented on msgraph/valuetypes.go
> +type AccessPackageCatalogState = string
Per compatibility note, can we keep both these types until such time as the beta API is updated

2021-12-20 09:54 UTC, manicminer commented on odata/types.go
> +	TypeAccessPackageMultipleChoiceQuestion                       Type = "#microsoft.graph.accessPackageMultipleChoiceQuestion"
Not sure why the linter didn't pick this up, but could we tidy up the spacing for these?

2021-12-22 16:16 UTC, kaovd commented
Seems the test for AppRoleAssignedToClient.Assign is having issues @manicminer - do you want to try fix within the PR or just do it in as seperate fix

2022-01-06 10:09 UTC, kaovd commented
Have synced with main build now passing @manicminer

2022-01-10 11:54 UTC, kaovd commented
AccessPackageResourceRequests tests are now failing for some reason likely may have changed MS side need to review

2022-01-15 17:48 UTC, kaovd commented
```
> $ go test -race ./msgraph -run="AccessPackage*" -v                                                                                                              [±fix/identitygovernance ✓]
=== RUN   TestAccessPackageClient
--- PASS: TestAccessPackageClient (8.86s)
=== RUN   TestAccessPackageAssignmentPolicyClient
--- PASS: TestAccessPackageAssignmentPolicyClient (4.77s)
=== RUN   TestAccessPackageCatalogClient
--- PASS: TestAccessPackageCatalogClient (1.63s)
=== RUN   TestAccessPackageResourceRequestClient
--- PASS: TestAccessPackageResourceRequestClient (18.34s)
=== RUN   TestAccessPackageResourceRoleScopeClient
--- PASS: TestAccessPackageResourceRoleScopeClient (17.03s)
PASS
ok      github.com/manicminer/hamilton/msgraph  50.657s
```
Can you give these tests a run locally @manicminer - I am not quite sure what the issues is with the CI but tests seem broken, but this passes fine for me locally

2022-01-17 10:08 UTC, manicminer approved these changes
Hi @kaovd, thanks for working on fixing this up, and sorry for the delay in reviewing. The test failure looks like a race condition stemming from the group creation - adding a sleep after line 21 in accesspackageresourcerequest_test.go seems to mitigate but we can leave that for now in lieu of a more robust way to handle propagation delays.

This LGTM! 🚀

2022-01-17 12:22 UTC, merged