[WIP]: create resource `azuread_user_license`
manicminer/hamilton pull request #239
Opened 2023-04-04 14:59 UTC by drewmullen

Hello! This is my first time working with the azuread provider or the go sdk yall have created to work with azure's graph api. I do have some experience writing features for the aws provider though! I'm creating this PR to show updates to this request and ask questions... Relates to issue: https://github.com/hashicorp/terraform-provider-azuread/issues/1057

Likely this will take me a while to get my arms fully around and finalize... if maintainers feel like adding commits, ill check this PR for any added commits before i make my next additions.

My plan:
 - [x] hamilton: create Create and Read functions
 - [ ] provider: create and test create/read handler 
 - [ ] hamilton: implement delete functions 
 - [ ] hamilton: add unit tests 
 - [ ] provider: create delete handler 
 - [ ] provider: create acc tests

2023-04-11 17:06 UTC, manicminer requested changes
@drewmullen Thank you for opening this PR! I've taken a look through and this is off to a good start. I've made some comments below, if you can take a look at these then I'll be happy to review again. Thanks!

2023-04-11 17:06 UTC, manicminer commented on msgraph/models.go
> +	SkuId *string `json:"skuId"`
Looks like this is missing the `disabledPlans` field?

2023-04-13 20:43 UTC, manicminer commented
@drewmullen No worries, the PR will be here waiting whenever you're able to work on it :)

2024-06-05 23:47 UTC, manicminer commented
Hi @drewmullen, just checking in to see if you might want to take another look at this? No worries if not, I'll go ahead and close it off and we can revisit again in future.

2024-06-06 00:08 UTC, drewmullen commented
We can close this. I may come back to it someday but we found a work around

thank you for the support!

2024-06-06 00:08 UTC, closed without merging