Add `updateAllowedCombinations` to `AuthenticationStrengthPoliciesClient`
manicminer/hamilton pull request #257
Opened 2023-08-14 14:41 UTC by alexwilcox9

It turns out you can't update the `allowedCombinations` field using the normal update endpoint. You'll get the following error
```
AuthenticationStrengthPoliciesClient.BaseClient.Patch(): unexpected status 405 with OData error: methodNotAllowed: Combinations can only be updated using updateAllowedCombinations action.: Combinations can only be updated
│ using updateAllowedCombinations action.
```
Instead there is a specific endpoint you must use documented here:
https://learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-1.0&tabs=http

Currently I'm passing through the whole `AuthenticationStrengthPolicy` object but technically it should only be the `allowedCombinations` field without the display name etc.
If it's preferred I can create an object that only has `allowedCombinations` for use here but wasn't sure if that was needed given that Graph seems to ignore the extra fields

2023-08-14 20:14 UTC, manicminer requested changes
Hi @alexwilcox9, thanks for this. I think we should build a new struct with the appropriate fields, since the API could at any time start throwing errors with the extra fields. We can still receive an `AuthenticationStrengthPolicy` as a method argument, and just pull out the `ID` and `AllowedCombinations` fileds. Other than that, this looks great 👍

2023-08-14 20:14 UTC, manicminer commented on msgraph/authentication_strength_policy.go
> +func (c *AuthenticationStrengthPoliciesClient) UpdateAllowedCombinations(ctx context.Context, Policy AuthenticationStrengthPolicy) (int, error) {
Can we camelcase this local variable?

```suggestion
func (c *AuthenticationStrengthPoliciesClient) UpdateAllowedCombinations(ctx context.Context, policy AuthenticationStrengthPolicy) (int, error) {
```

2023-08-14 23:22 UTC, alexwilcox9 commented
Thanks for the feedback @manicminer, I've updated the code to create a new `AuthenticationStrengthPolicy` with only the `allowedCombinations` field set.

Is this sufficient or should I create a new struct in models.go for use here?

2023-09-25 19:06 UTC, manicminer approved these changes
@alexwilcox9 Sorry for the delay, I think this is fine to construct a request like this and we don't need to define a new exported struct type for it. Thanks for this!

2023-09-25 19:07 UTC, merged