Fix missing odata type for externalTenants configuration
manicminer/hamilton pull request #264
Opened 2023-10-26 18:10 UTC by agileknight

Without setting the correct @odata.type for both
possible values all and enumerated, a patch will fail when first enumerating and setting members and then changing to type all because the stored object
is of the wrong type.

References #261

2023-10-26 23:08 UTC, manicminer requested changes
@agileknight Thanks again for working on this. This mostly LGTM, just a couple of refactoring suggestions below if you can take a look?

2023-10-26 23:08 UTC, manicminer commented on msgraph/models.go
> +	setExternalTenantsObjectType(guestOrExternalUsers.conditionalAccessGuestsOrExternalUsers)
As there's no need for reusability here, could we simplify this by forgoing the constant declarations and move the `if`+`switch` blocks out into the parent method, dropping the anonymous func? The anonymous struct embeds a pointer to the original struct so this should work?

```suggestion
	if c.ExternalTenants != nil && c.ExternalTenants.MembershipKind != nil {
		switch *c.ExternalTenants.MembershipKind {
		case ConditionalAccessExternalTenantsMembershipKindAll:
			c.ExternalTenants.ODataType = utils.StringPtr("#microsoft.graph.conditionalAccessAllExternalTenants")
		case ConditionalAccessExternalTenantsMembershipKindEnumerated:
			c.ExternalTenants.ODataType = utils.StringPtr("#microsoft.graph.conditionalAccessEnumeratedExternalTenants")
		}
	}
```

2023-10-26 23:08 UTC, manicminer commented on msgraph/conditionalaccesspolicy_test.go
> +}
This might be a useful function to move into the `internal/test` package?

2023-10-26 23:20 UTC, manicminer approved these changes
@agileknight I hope you don't mind, in the interest of getting this in for a release today, I've committed my review suggestions and will tag this shortly. Appreciate the work on this!

2023-10-26 23:28 UTC, merged

2023-10-27 08:50 UTC, philippdevtech commented
@manicminer Thanks, I like the changes you made!